### ISSUE TITLE
UI Rewrite

### ISSUE THREAD

**Issue by CommandCrafterHD** [Metis-Team/mts_marker#38]
To accomodate the Timestamps and Moving indicators, the UI needs to be redesigned ground up.
This is how the new UI could look.
It would have the preview window on the left side, the Marker Config in the middle and presets on the right.
![23-08-2021_654 1](https://user-images.githubusercontent.com/23524203/130486136-7287c59b-5cdf-4203-b995-64e9752f9c33.png)

- [ ] Marker components larger than one field (e.g. a dropdown) should be hidden behind a button which leads to a new submenu
- [ ] Octagon in middle
- [ ] Marker components should be located at the corresponding amplifier fields

**Comment by Timi007** [comment]
The UI elements should be located at the corresponding amplifier fields:
![image](https://user-images.githubusercontent.com/9505872/130491859-c06ac9dd-543e-4c58-8252-efb4e364b573.png)
The hexagon in the middle should be the placeholder for each identity containing the icon and modifier UI elements.
![image](https://user-images.githubusercontent.com/9505872/130492173-6ce0d8e5-e7da-49ab-9f12-cb529f870d7d.png)

**Comment by Timi007** [comment]
Octagon in middle of the UI:

![Octagon](https://user-images.githubusercontent.com/9505872/131372336-ec695120-9944-43f5-aca1-7f65f9965966.png)
