### ISSUE TITLE
Make Higher Formation behave like Unique Identifier

### ISSUE THREAD

**Issue by CommandCrafterHD** [Metis-Team/mts_marker#40]
Change the "Higher Formation" field to work similar to the "Unique Identifier", which would move it to the bottom right, instead of just being to the right of the marker, but also limit it's length.
Additionally, create a new field, which works like the "Higher Formation" field now does.
This field would be called "Additional Information"

**Comment by Timi007** [comment]
![Arma_Marker_Font](https://user-images.githubusercontent.com/9505872/130490998-dcda0fe9-ea59-4105-a945-631df400a046.png)
Arma uses a slightly different font of RobotoCondensedBold. Therefore we should stick to the Roboto type family and use [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono).
