### ISSUE TITLE
Extend public marker API

### ISSUE THREAD

**Issue by Timi007** [Metis-Team/mts_marker#68]
**Is your feature request related to a problem? Please describe.**

Extend the current public API for manipulating and getting marker information.

**Describe the solution you'd like**

Add following API similar to vanilla except with our marker prefix:

- [x] `mts_markers_fnc_getAllMarkers`
  - *Args:* Include non-editable markers (optional, default: true).
  - *Returns:* Array of all Metis marker prefixes currently on the map.
  - Vanilla equivalent: [allMapMarkers](https://community.bistudio.com/wiki/allMapMarkers)
- [x] `mts_markers_fnc_getMarkerPos`
  - *Args:* Marker prefix (string); Preserve elevation (optional, default: false).
  - *Returns:* Position3D in format `[x,y,0]` or PositionAGL. Reason: Same return value as vanilla `getMarkerPos` for compatibility.
  - Vanilla equivalent: [getMarkerPos](https://community.bistudio.com/wiki/getMarkerPos)
- [x] `mts_markers_fnc_getMarkerSize`
  - *Args:* Marker prefix (string).
  - *Returns:* Scale of marker as a number. This deviates from vanilla but is more consitent with our `_scale` argument in `mts_markers_fnc_createMarker`.
  - Vanilla equivalent: [getMarkerSize](https://community.bistudio.com/wiki/getMarkerSize)
- [x] `mts_markers_fnc_getMarkerType` (or `mts_markers_fnc_getMarkerConfig`)
  - *Args:* Marker prefix (string).
  - *Returns:* Same `_markerParameter` array as in `mts_markers_fnc_createMarker`.
  -  Vanilla equivalent: [getMarkerType](https://community.bistudio.com/wiki/getMarkerType)
- [x] `mts_markers_fnc_getPlayerID`
  - *Args:* Marker prefix (string).
  - *Returns:* Player ID string or `"-1"` if not available.
  - Vanilla equivalent: [getPlayerID](https://community.bistudio.com/wiki/getPlayerID)

We also could add functions to modify alpha:

- [x] `mts_markers_fnc_setMarkerAlpha`
  - *Args:* Marker prefix (string); Alpha value (0-1).
  - *Returns:* Nothing.
  - Vanilla equivalent: [setMarkerAlpha](https://community.bistudio.com/wiki/setMarkerAlpha)
- [x] `mts_markers_fnc_setMarkerAlphaLocal`
  - *Args:* Marker prefix (string); Alpha value (0-1).
  - *Returns:* Nothing.
  - Vanilla equivalent: [setMarkerAlphaLocal](https://community.bistudio.com/wiki/setMarkerAlphaLocal)
- [x] `mts_markers_fnc_getMarkerAlpha`
  - *Args:* Marker prefix (string).
  - *Returns:* Number (0-1).
  - Vanilla equivalent: [markerAlpha](https://community.bistudio.com/wiki/markerAlpha)

**Comment by PhILoXs** [comment]
Alpha set/get API will be done in another PR. This will introduce a new argument to the marker createn.

**Comment by PhILoXs** [comment]
Both PRs are merged.
