### ISSUE TITLE
Feature request: the HQ symbol

### ISSUE THREAD

**Issue by bendy101** [Metis-Team/mts_marker#73]
was amazed to see this mod doesnt have one of the most important markers, the HQ!!

it looks like this:

blufor:
https://commons.wikimedia.org/wiki/File:NATO_Map_Symbol_-_Friendly_Headquarters.svg

opfor
https://commons.wikimedia.org/wiki/File:NATO_Map_Symbol_-_Enemy_Headquarters.svg

please add :)

**Comment by Timi007** [comment]
Duplicate of #46
